# Build Docs using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
 vmImage: win1803

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: 10.x
    - script: npm install
    - script: npm build
    - script: git -v
    - script: yarn -v