# Build Docs using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
 vmImage: win1803

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: 10.x
    - script: npm install
    - script: npm run build
    - powershell: |
        git clone https://github.com/xxred/xxred.github.io.git -b gh-pages origin_site -q
        rm origin_site/* -recurse
        Copy-Item origin_site/.git vuepress -recurse
        CD vuepress
        git add -A 2>&1
        git commit -m "CI Updates" -q
        git push origin master -q
        write-host '发布成功'